---
# tasks file for nginx

- name: installation du dépot epel-release
  yum:
   name: epel-release
   state: present
   
- name: installation du serveur web nginx
  yum:
   name: nginx
   state: present

- name: "création de l'arborescence html pour les sites {{ sites }}"
  file:
    path: /var/www/{{ item }}/html
    owner: root
    group: root
    mode: 0755
    recurse: true
    state: directory
  loop:
    "{{ sites }}"

- name: "Création des fichiers index.html pour les {{ sites }}"
  template:
    src: index.html.j2
    dest: /var/www/{{ item }}/html/index.html
    mode: 0755
  loop:
   "{{ sites }}"

- name: "création de l'arborescence pour les sites disponibles et actifs"
  file:
    path: /etc/nginx/sites-{{ item }}
    owner: root
    group: root
    mode: 0755
    recurse: true
    state: directory
  loop:
   - available
   - enabled
- name: Configuration de nginx.conf
  blockinfile:
    path: /etc/nginx/nginx.conf
    insertbefore: "^# Settings"
    content: |
       "        include /etc/nginx/sites-enabled/*.conf;"
       "         server_names_hash_bucket_size 64;"

- name: "Configuration des sites {{ sites }}"
  template:
    src: sites.conf.j2
    dest: "/etc/nginx/sites-available/{{ item }}.conf"
  loop:
    "{{ sites }}"

- name: "activation des sites web {{ sites }}"
  file:
    src: /etc/nginx/sites-available/{{ item }}.conf
    dest: /etc/nginx/sites-enabled/{{ item }}.conf
    state: link
  loop:
    "{{ sites }}"
  notify: start_nginx 
